name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore /home/runner/work/TechnicalTestAPI/TechnicalTestAPI/ReservationsAPI/
    - name: Build
      run: dotnet build --no-restore /home/runner/work/TechnicalTestAPI/TechnicalTestAPI/ReservationsAPI/
